### ISSUE TITLE
error building package

### ISSUE THREAD

**Issue by jmfa** [kche309/beast-phylonco#1]
Hi,

Wonderful to see this exciting package out! 
I'm trying to build it using the `ant addon` command but it keeps failing with the following error message:

```
Buildfile: /home/beast-phylonco/build.xml

BUILD FAILED
/home/beast-phylonco/build.xml:32: The following error occurred while executing this line:
/home/beast2/build.xml:298: taskdef class net.jsign.JsignTask cannot be found
```

I've downloaded and built the latest versions of BEAST2 and BEAST Labs from source.
Any idea of what might be causing this error?

Thanks in advance,
J

**Comment by kche309** [comment]
Hi Joao, 

Thanks for trying out my package. It may be a BEAST building error.
Could you send me your OS version details so I can look into it?

Many thanks,
Kylie

**Comment by elliott-wen** [comment]
Hi Kylie, 

I encountered the same error but managed to fix it by myself. I guess Beast developers introduced a bug in the upstream branch. 

Cheers
Elliott

**Comment by kche309** [comment]
Hi Joao, 

After some investigating, it seems BEAST2 needs to be built using `ant windows` before building the package with `ant addon`. 

I have updated the instructions in the readme to reflect this. 

I will make the package available via the BEAST2 package manager in the next few days, which should hopefully remedy any install issues.

Thanks, 
Kylie

**Comment by jmfa** [comment]
Hi Kylie, 

Thanks for your help.
I managed to build it with the new instructions. ;)

Cheers,
J

**Comment by kche309** [comment]
Hi Joao, 

Great, I'm very happy to hear it worked for you :) 

Cheers, 
Kylie
